Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cff7528ff583bf9a
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation]]
